#
# Configuration for Cirrus CI tests
#

checkout_and_setup_task_template: &SETUP_TASK_TEMPLATE
  env_info_script: |
    # display data about Python interpreter
    set -e
    echo "Python executable: $(command -v python)"
    echo "Python version: $(python -V 2>&1)"
  dependencies_script: |
    # Python deps
    case $(python V 2>&1) in
      'Python 2.7'*)
        # as of 2021-01-05, setuptools 51 and pip 21 have dropped support
        # for Py 2.7 completely, so we need to use earlier versions to
        # continue testing
        pip install --upgrade 'setuptools<=44.1.1' 'pip==20.3.3' ;;
      'Python 3.'*)
        pip install --upgrade 'setuptools>=21' 'pip>=9.0.0' ;;
    esac


task:
  <<: *SETUP_TASK_TEMPLATE
  name: Unit Tests
  setup_script: |
    pip install -e '.[daemon,ec2,openstack,optimizer]'
  test_script: |
    set -e
    pip install 'pytest>=4.1' 'pytest-cov' 'pytest-coverage' 'mock' 'tox' 'codecov'
    export BOTO_CONFIG=/dev/null
    pytest -v --cov=gc3libs --cov-branch --ignore install.py
    codecov
    echo "OK: GC3Pie's unit tests successfully performed."
    exit 0
  matrix:
    - container:
        image: python:2.7
      allow_failures: true
    - container:
        image: python:3.6
    - container:
        image: python:3.7
    - container:
        image: python:3.8
    - container:
        image: python:3.9


task:
  <<: *SETUP_TASK_TEMPLATE
  name: Install Script Tests
  setup_script: |
    python ./install.py --version
  # Run the install script on multiple platforms
  test_script: |
    set -e
    python ./install.py --development --remove-target-dir --target $PWD/venv --yes
    . venv/bin/activate
    gc3utils servers
    echo "OK: GC3Pie successfully installed."
    exit 0
  matrix:
    - compute_engine_instance:
        image_project: centos-cloud
        image: family/centos-7
    - compute_engine_instance:
        image_project: centos-cloud
        image: family/centos-8
    - compute_engine_instance:
        image_project: debian-cloud
        image: family/debian-9-stretch
    - compute_engine_instance:
        image_project: debian-cloud
        image: family/debian-10-buster
    - compute_engine_instance:
        image_project: ubuntu-os-cloud
        image: family/ubuntu-1604-xenial
    - compute_engine_instance:
        image_project: ubuntu-os-cloud
        image: family/ubuntu-1804-bionic
    - compute_engine_instance:
        image_project: ubuntu-os-cloud
        image: family/ubuntu-2004-focal
    - compute_engine_instance:
        image_project: ubuntu-os-cloud
        image: family/ubuntu-2010-groovy
    - macos_instance:
        image: big-sur-base
    - macos_instance:
        image: catalina-base
