language: python
python:
  - "2.6"
  - "2.7"
addons:
  apt:
    packages:
    - time
install:
  - "pip install --upgrade setuptools pip"
  - "pip install 'pytest==3.2.5' mock"
  - "pip install -e .[openstack,ec2,daemon]"
script: pytest -v
