# FORTRAN90 compiler
F90 = gfortran

# FOTRAN compiler flags
F90FLAGS = -g -O3 -static

vfi.exe: vfi.f90
	$(F90) $(F90FLAGS) vfi.f90 -o vfi.exe


# # path to the C++ compiler
# CXX = g++
#
# # favorite C++ compiler flags
# CXXFLAGS = -g -O3 -DNDEBUG
#
# vfi.exe: vfi.cpp
# 	$(CXX) $(CXXFLAGS) vfi.cpp -o vfi.exe