#! /bin/sh
### BEGIN INIT INFO
# Provides:          a4mesh
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Run ggeosphere simulations
# Description:       Scans an S3 Object Store and runs Ggeosphere
#                    simulations for each model file found.
#                    Monitors the S3 Object Store for new models.
### END INIT INFO

# Author: Sergio Maffioletti <sergio.maffioletti@uzh.ch>
# Do NOT "set -e"

######## Configuration for deplyment ###########
#
# Change these according to your actual deployment
#

# A4MESH_DIR: session, configuration file will be find there
A4MESH_DIR="/home/gc3-user/ggeosphere"

# Configuration for deployment
A4MESH_CONFIG="${A4MESH_DIR}/etc/a4mesh.cfg"

# Location of the session dir where execution information will be kept
SESSION_DIR="${A4MESH_DIR}/session"

# GGEOSPHERE: location of the ggeosphere python script
GGEOSPHERE="/home/gc3-user/gc3pie/src/gc3apps/a4mesh/ggeosphere.py"

# GC3PIE_VIRTUALENV: virtualenv, if needed
GC3PIE_VIRTUALENV="/home/gc3-user/gc3pie"

###################
#
# PATH should only include /usr/* if it runs after the mountnfs.sh script
DESC="A4Mesh"
NAME="ggeosphere"
PIDFILE=/var/tmp/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

PATH=/usr/local/bin:/sbin:/usr/sbin:/bin:/usr/bin:${A4MESH_DIR}/bin

SESSION_NAME="ggeosphere"

GGEOSPHERE_ARGS="-c ${A4MESH_CONFIG} -s ${SESSION_DIR}/${SESSION_NAME} -C60"

# Enable GC3Pie virtualenv
if [ ! -z "$GC3PIE_VIRTUALENV" ]; then
    . $GC3PIE_VIRTUALENV/bin/activate
fi

# Exit if the package is not installed
[ -x "$GGEOSPHERE" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

VERBOSE="yes"

#
# Function that starts the daemon/service
#
do_start()
{
	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running
	#   2 if daemon could not be started
	start-stop-daemon --start --pidfile $PIDFILE --exec $GGEOSPHERE --test > /dev/null \
		|| return 1
	start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --exec $GGEOSPHERE -- $GGEOSPHERE_ARGS
}

#
# Function that stops the daemon/service
#
do_stop()
{
	# Return
	#   0 if daemon has been stopped
	#   1 if daemon was already stopped
	#   2 if daemon could not be stopped
	#   other if a failure occurred
	start-stop-daemon --stop --retry=TERM/30/KILL/5 --pidfile $PIDFILE # --name $NAME
	RETVAL="$?"
	[ "$RETVAL" = 2 ] && return 2
	# Wait for children to finish too if this is a daemon that forks
	# and if the daemon is only ever run from this initscript.
	# If the above conditions are not satisfied then add some other code
	# that waits for the process to drop all resources that could be
	# needed by services started subsequently.  A last resort is to
	# sleep for some time.
	# start-stop-daemon --stop --oknodo --retry=0/30/KILL/5 --exec $GGEOSPHERE
	# [ "$?" = 2 ] && return 2
	# Many daemons don't delete their pidfiles when they exit.
	rm -f $PIDFILE
	return "$RETVAL"
}

#
# Function that sends a SIGHUP to the daemon/service
#
do_reload() {
	#
	# If the daemon can reload its configuration without
	# restarting (for example, when it is sent a SIGHUP),
	# then implement that here.
	#
	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
	return 0
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  status)
	status_of_proc -p $PIDFILE "$GGEOSPHERE" "$NAME" && exit 0 || exit $?
	;;
  restart)
	#
	# If the "reload" option is implemented then remove the
	# 'force-reload' alias
	#
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
			0) log_end_msg 0 ;;
			1) log_end_msg 1 ;; # Old process is still running
			*) log_end_msg 1 ;; # Failed to start
		esac
		;;
	  *)
		# Failed to stop
		log_end_msg 1
		;;
	esac
	;;
  *)
	#echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	echo "Usage: $SCRIPTNAME {start|stop|status|restart}" >&2
	exit 3
	;;
esac

:
