.. Hey, Emacs this is -*- rst -*-

   This file follows reStructuredText markup syntax; see
   http://docutils.sf.net/rst.html for more information.

.. This file is included by *any* other ``.txt`` file. 
   Be careful!!!


.. Links

   Please list here all references that (are likely to) appear in more
   than one file, so to avoid "duplicate link" errors and to control
   the reference target more easily.

   References should be sorted by link name (case-insensitively), to
   make it easy to spot a missing or duplicate reference.


.. _GAMESS: http://www.msg.ameslab.gov/gamess/
.. _GC3Pie: http://gc3pie.googlecode.com/
.. _`GC3Pie mailing list`: mailto:gc3pie@googlegroups.com
.. _`Grid Engine`: http://gridengine.org/blog/2011/11/23/what-now/
.. _NorduGrid: http://www.nordugrid.org/
.. _Rosetta: http://www.rosettacommons.org/
.. _SMSCG: http://www.smscg.ch/
.. _Subversion: http://subversion.apache.org/
.. _SWITCHaai: http://www.switch.ch/aai
