#!/usr/bin/env python
from optparse import OptionParser
from ase.calculators.jacapo import *
from Scientific.IO.NetCDF import NetCDFFile as NetCDF
import os

os.environ['DACAPO_READONLY'] = 'On'

parser = OptionParser(usage='ncsum',
                      version='0.1')
parser.add_option('-e',
                  nargs=0,
                  help = 'print only the energy')

options,args = parser.parse_args()

for arg in args:

    calc = Jacapo(arg)

    if options.e is not None:
        nc = netCDF(arg,'r')
        energy = nc.variables.get('TotalEnergy',None)
        if energy is not None:
            print energy[:][-1]
        else:
            print None
        nc.close()
    else:
        print calc

