#!/usr/bin/env python

__author__="Sergio Maffioletti (sergio.maffioletti@gc3.uzh.ch)"
__date__="01 february 2010"
__copyright__="Copyright 2009 2011 Grid Computing Competence Center - UZH/GC3"
__version__="0.2"

import sys
sys.path.append('/opt/nordugrid/lib/python2.3/site-packages')
sys.path.append('/home/sergio/dev/gc3/gc3utils/branches/sergio/gc3utils/gc3utils')
import utils

def checkCredential(): 

    email_contact="sergio.maffioletti@gc3.uzh.ch"
    exitCode=1
    email_text='''
Please renew your Grid credential.
Log in your GC3 client machine and issue: grid-credential-renew.

GC3 team.''' 
    try:
        if ( (not utils.CheckGridAuthentication()) | (not utils.checkUserCertificate()) ):
            print 'Sending email notification'
            utils.send_email(email_contact,"info@gc3.uzh.ch","GC3 Warning: Renew Grid credential",email_text)
        else:
            exitCode = 0
    except:
        print "failed: "+str(sys.exc_info()[1])

    return exitCode

if __name__ == "__main__":
    sys.exit(checkCredential())
