#!/bin/bash

echo Start

# readig input parameters
f=$1;
c=$2;
t=$3;
archive=$4;

# open archive
echo -n "opening archive... "
tar xfz $archive
if [ ! $? -eq 0 ]; then
    echo "[ failed ]"
    exit 1
else
    echo "[ ok ]"
fi

echo -n "Checking required commands... "
if [ ! -e ./gnfs-lasieve6 ]; then
    echo "[ failed on ./gnfs-lasieve6 ]"
    exit 1
fi

if [ ! -e ./tdsievemt ]; then
    echo "[ failed on ./tdsievemt ]"
    exit 1
fi
echo "[ ok ]"

chmod u+x gnfs-lasieve6
chmod u+x tdsievemt
mkdir pprod

let j=$f+$c;

A=37;
if [ $f -ge 400000000 ]; then A=35; fi
if [ $f -ge 1500000000 ]; then A=33; fi

name="M8o_200"; 
if [ $f -ge 300000000 ]; then name="M8o_300"; fi
if [ $f -ge 400000000 ]; then name="M8o_400"; fi
if [ $f -ge 600000000 ]; then name="M8o_600"; fi
if [ $f -ge 800000000 ]; then name="M8o_800"; fi
if [ $f -ge 1200000000 ]; then name="M8o_1200"; fi
if [ $f -ge 1500000000 ]; then name="M8o_1500"; fi
if [ $f -ge 2000000000 ]; then name="M8o_2000"; fi
if [ $f -ge 3000000000 ]; then name="M8o_3000"; fi
if [ $f -ge 4200000000 ]; then name="M8o_4200"; fi

echo "alg sieve for $name, A=$A, $c spq in $f-$j";
./gnfs-lasieve6 -t $t -b $name -avvDoW0s -A $A -f $f -c $c
iname=$name.lasieve-0.$f-$j.ab
cat $name.lasieve-0.$f-$j.ab.nb2? $name.lasieve-0.$f-$j.ab.nb3[0-4] > $iname

echo "tdsieve 991";
./tdsievemt -t $t -b M991 -vs -a 500000000,99 -i $iname
gzip M991.tdsieve.$f-$j
cat $name.lasieve-0.$f-$j.ab.nb35 >> $name.lasieve-0.$f-$j.ab
echo "tdsieve 1081";
./tdsievemt -t $t -b M1081 -vs -a 500000000,103 -i $iname
gzip M1081.tdsieve.$f-$j
echo "tdsieve 1111";
./tdsievemt -t $t -b M1111 -vs -a 500000000,103 -i $iname
gzip M1111.tdsieve.$f-$j
echo "tdsieve 1129";
./tdsievemt -t $t -b M1129 -vs -a 500000000,103 -i $iname
gzip M1129.tdsieve.$f-$j
cat $name.lasieve-0.$f-$j.ab.nb36 >> $name.lasieve-0.$f-$j.ab
echo "tdsieve 1151";
./tdsievemt -t $t -b M1151 -vs -a 500000000,105 -i $iname
gzip M1151.tdsieve.$f-$j
echo "tdsieve 1153";
./tdsievemt -t $t -b M1153 -vs -a 500000000,105 -i $iname
gzip M1153.tdsieve.$f-$j
echo "tdsieve 1159";
./tdsievemt -t $t -b M1159 -vs -a 500000000,105 -i $iname
gzip M1159.tdsieve.$f-$j
cat $name.lasieve-0.$f-$j.ab.nb37 >> $name.lasieve-0.$f-$j.ab
echo "tdsieve 1177";
./tdsievemt -t $t -b M1177 -vs -a 2000000000,138 -i $iname
gzip M1177.tdsieve.$f-$j
echo "tdsieve 1193";
./tdsievemt -t $t -b M1193 -vs -a 2000000000,141 -i $iname
gzip M1193.tdsieve.$f-$j
echo "tdsieve 1199";
./tdsievemt -t $t -b M1199 -vs -a 2000000000,141 -i $iname
gzip M1199.tdsieve.$f-$j

rm $iname
rm $name.lasieve-0.$f-$j.ab.nb??
rm -r pprod

echo "Collecting results to output file... "
for i in *.gz
do
	echo $i \"\" >> output.files
done

echo Done
